#!/usr/bin/env python3
"""Math AI v5 — DeepMind-only release trainer.

Contract:
- Training data: ONLY official pre-generated DeepMind Mathematics Dataset v1.0 files.
- Train splits: train-easy / train-medium / train-hard.
- Modules: algebra__linear_1d / algebra__linear_2d / algebra__polynomial_roots.
- No project synthetic generator.
- No algebraic augmentation generated by this project.
- Audit: ONLY official DeepMind interpolate / extrapolate generators, with synthetic fallback forbidden.
"""

import importlib.util
import pathlib
import shutil
import urllib.request

SOURCE_COMMIT = "__SOURCE_COMMIT__"
CORE_COMMIT = "3a6fbc9036d6b4cac9f7c9e4e38faabae19659ce"
CORE_URL = f"https://raw.githubusercontent.com/msabz/Al/{CORE_COMMIT}/kaggle/kaggle_train.py"
CORE_PATH = pathlib.Path("/kaggle/working/_mathai_kaggle_core.py")

urllib.request.urlretrieve(CORE_URL, CORE_PATH)
spec = importlib.util.spec_from_file_location("mathai_kaggle_core", CORE_PATH)
if spec is None or spec.loader is None:
    raise RuntimeError("Could not load Kaggle orchestration core")
core = importlib.util.module_from_spec(spec)
spec.loader.exec_module(core)

core.SOURCE_COMMIT = SOURCE_COMMIT
core.TOTAL_STEPS = 40_000
core.BATCH_SIZE = 4096
core.LEARNING_RATE = 2.0e-4
core.MIN_LEARNING_RATE = 2.0e-5
core.WARMUP_STEPS = 800
core.CONSISTENCY_WEIGHT = 0.0
core.DEEPMIND_RATIO = 1.0
core.DEEPMIND_PER_FILE = 150_000
core.SYNTHETIC_POOL_SIZE = 0


def _replace_function(text, name, next_name, replacement):
    start = text.index(f"def {name}(")
    end = text.index(f"\n\ndef {next_name}(", start)
    return text[:start] + replacement.rstrip() + "\n\n" + text[end + 2:]


_original_prepare_source = core.prepare_source


def prepare_source_deepmind_only(log_fh):
    actual = _original_prepare_source(log_fh)

    audit_path = core.ROOT / "colab/generalization_audit.py"
    text = audit_path.read_text()

    text = _replace_function(text, "build_strict_ood", "build_fresh_iid", r'''def build_strict_ood(ns, count=256):
    # Official DeepMind extrapolation only. No local synthetic generator.
    return build_deepmind_split(ns, "extrapolate", count, seed_salt=0x5A170002)''')

    text = _replace_function(text, "build_fresh_iid", "build_deepmind_split", r'''def build_fresh_iid(ns, count=256):
    # Official DeepMind interpolation only. Independent seed from the other bank.
    return build_deepmind_split(ns, "interpolate", count, seed_salt=0x1A2B0001)''')

    text = _replace_function(text, "build_deepmind_split", "equivalent_add_constant", r'''def build_deepmind_split(ns, split="interpolate", count=192, seed_salt=0):
    dm_algebra = ns["dm_algebra"]
    old_modules = ns["dm_modules"]
    old_names = list(ns["DM_NAMES"])
    old_synthetic = ns["synthetic"]

    def synthetic_forbidden(*args, **kwargs):
        raise RuntimeError("__PROJECT_SYNTHETIC_FORBIDDEN__")

    try:
        ns["synthetic"] = synthetic_forbidden
        if split == "interpolate":
            ns["dm_modules"] = dm_algebra.test()
            ns["DM_NAMES"] = ["linear_1d", "linear_2d", "polynomial_roots"]
            base_seed = 0xD33F0001
        elif split == "extrapolate":
            ns["dm_modules"] = dm_algebra.test_extra()
            ns["DM_NAMES"] = ["polynomial_roots_big"]
            base_seed = 0xD33F0002
        else:
            raise ValueError(split)

        rng = random.Random(base_seed ^ int(seed_salt))
        result = []
        seen = set()
        attempts = 0
        while len(result) < count and attempts < count * 1200:
            attempts += 1
            try:
                ex = ns["deepmind_example"](rng)
            except Exception:
                continue
            # This is a declared numeric support-domain filter, not a data-validity filter.
            if target_magnitude(ex) > 300.0:
                continue
            if ex["eq"] in seen:
                continue
            seen.add(ex["eq"])
            result.append(ex)

        if len(result) < max(64, count // 2):
            raise RuntimeError(f"Official DeepMind {split} produced only {len(result)} usable examples")
        return result
    finally:
        ns["synthetic"] = old_synthetic
        ns["dm_modules"] = old_modules
        ns["DM_NAMES"] = old_names''')

    text = _replace_function(text, "consistency_audit", "improvement", r'''def consistency_audit(ns, model, examples, limit=128):
    # Deliberately disabled: user requires no project-generated transformed equations.
    # Generalization is measured only on independent official DeepMind splits.
    return {
        "checked": 0,
        "family_mismatch": 0,
        "mean_slot_delta": 0.0,
        "mean_presence_delta": 0.0,
        "mean_state_kl": 0.0,
        "transformation": "disabled; no project-generated augmentation allowed",
        "disabled_reason": "DeepMind-only contract",
    }''')

    text = text.replace(
        'dm_interp = build_deepmind_split(ns, "interpolate", 192)',
        'dm_interp = build_deepmind_split(ns, "interpolate", 192, seed_salt=0x33000003)',
        1,
    )
    text = text.replace(
        'dm_extra = build_deepmind_split(ns, "extrapolate", 128)',
        'dm_extra = build_deepmind_split(ns, "extrapolate", 128, seed_salt=0x44000004)',
        1,
    )
    text = text.replace(
        '"fresh_iid": "independent RNG stream, same nominal range, never used by optimizer",',
        '"fresh_iid": "independent official DeepMind interpolate bank; no project synthetic data",',
        1,
    )
    text = text.replace(
        '"strict_ood": "finite targets with |solution| >= 135 while training synthetic range <= 100",',
        '"strict_ood": "independent official DeepMind extrapolate bank; no project synthetic data",',
        1,
    )
    text = text.replace(
        '"equivalence": "+37 added to both sides, a transformation not used as the training consistency pair",',
        '"equivalence": "disabled by DeepMind-only contract; no project-generated transformed equations",',
        1,
    )
    audit_path.write_text(text)
    print("[DEEPMIND-ONLY] Audit patched: official interpolate/extrapolate only", flush=True)
    return actual


core.prepare_source = prepare_source_deepmind_only
_original_prepare_turbo_worker = core.prepare_turbo_worker


def prepare_turbo_worker_deepmind_only():
    worker = _original_prepare_turbo_worker()
    text = worker.read_text()

    # Correct parser adaptation. DeepMind data is not altered; only our reader is fixed.
    old_parser = 'parts = [x.strip() for x in body.split(" and ") if "=" in x]'
    new_parser = 'parts = [x.strip() for x in re.split(r"\\s*(?:,|\\band\\b)\\s*", body) if "=" in x]'
    if old_parser not in text:
        raise RuntimeError("linear_2d parser target not found")
    text = text.replace(old_parser, new_parser, 1)

    old_affine = 'tree = ast.parse(expr.replace("^", "**"), mode="eval")'
    new_affine = 'tree = ast.parse(expr.strip().replace("^", "**"), mode="eval")'
    if old_affine not in text:
        raise RuntimeError("affine whitespace target not found")
    text = text.replace(old_affine, new_affine, 1)

    # No project-generated equivalent equations.
    text = text.replace('return mk(equation, [value], equiv=swap(equation))', 'return mk(equation, [value], equiv=None)', 1)
    text = text.replace('return mk(text, system=system, equiv=";".join(reversed(renamed)))', 'return mk(text, system=system, equiv=None)', 1)
    text = text.replace('return mk(equation, sorted(set(roots)), equiv=swap(equation))', 'return mk(equation, sorted(set(roots)), equiv=None)', 1)

    # Coverage guard: every official train file must actually contribute examples.
    old_coverage = '    print(f"  ✓ accepted={accepted_here} / seen={seen_here} in {time.time()-t0:.1f}s")\ndm_writer.trim()'
    new_coverage = (
        '    if accepted_here < min(10000, DEEPMIND_PER_FILE):\n'
        '        raise RuntimeError(f"DeepMind coverage guard failed for {split_name}/{module}: accepted={accepted_here}, seen={seen_here}")\n'
        '    print(f"  ✓ accepted={accepted_here} / seen={seen_here} in {time.time()-t0:.1f}s")\n'
        'dm_writer.trim()'
    )
    if old_coverage not in text:
        raise RuntimeError("coverage guard target not found")
    text = text.replace(old_coverage, new_coverage, 1)

    # Remove local synthetic-pool creation completely.
    syn_start = text.index('banner("[4/8]')
    syn_end = text.index('\n\ndef pool_to_gpu', syn_start)
    text = text[:syn_start] + '''banner("[4/8] DeepMind-only dataset contract")
print("Synthetic pool  : DISABLED")
print("Augmentation    : DISABLED")
print("Training source : official pre-generated DeepMind files only")
''' + text[syn_end:]

    # Load only DeepMind pool to GPU.
    gpu_start = text.index('banner("[5/8]')
    gpu_end = text.index('\n\ndef take', gpu_start)
    text = text[:gpu_start] + '''banner("[5/8] تحميل DeepMind training pool إلى الـGPU")
dm_pool = pool_to_gpu(dm_writer, "DeepMind official")
del dm_writer
gc.collect()
torch.cuda.synchronize()
free_mem, total_mem = torch.cuda.mem_get_info()
print(f"GPU pool ready : DeepMind={dm_pool['size']:,} | synthetic=0")
print(f"VRAM used      : {human_bytes(total_mem-free_mem)} / {human_bytes(total_mem)}")
''' + text[gpu_end:]

    # Batch sampler: 100% DeepMind, and no second/equivalent input.
    take_start = text.index('def take(pool, count):')
    stable_start = text.index('\n\ndef stable_loss', take_start)
    text = text[:take_start] + '''def take(pool, count):
    idx = torch.randint(0, pool["size"], (count,), device=device)
    return (
        pool["k"][idx].long(),
        pool["n"][idx].float(),
        pool["d"][idx].float(),
        pool["f"][idx].long(),
        pool["r"][idx],
        pool["rc"][idx].long(),
        pool["sy"][idx],
        pool["st"][idx].long(),
        None,
    )


def mixed_batch(batch_size):
    return take(dm_pool, batch_size)
''' + text[stable_start:]

    # Avoid wasting half the compute on a disabled consistency branch.
    text = text.replace('o = train_model(k,n,d,f); oo = train_model(*eqv)', 'o = train_model(k,n,d,f); oo = None')
    text = text.replace('other = train_model(*eqv)', 'other = None')
    text = text.replace(
        'print(f"Samples/step   : {BATCH_SIZE:,} ({DEEPMIND_RATIO*100:.0f}% DeepMind / {(1-DEEPMIND_RATIO)*100:.0f}% synthetic)")',
        'print(f"Samples/step   : {BATCH_SIZE:,} (100% official DeepMind / 0% project synthetic)")',
        1,
    )

    # AMP dtype-safe systems target.
    old_dtype = 'assigned_vals[sysmask,:2] = systems[sysmask,:2] / ROOT_SCALE'
    new_dtype = 'assigned_vals[sysmask,:2] = (systems[sysmask,:2] / ROOT_SCALE).to(out.dtype)'
    if old_dtype in text:
        text = text.replace(old_dtype, new_dtype, 1)

    worker.write_text(text)
    print("[DEEPMIND-ONLY] Training contract verified: 100% official DeepMind", flush=True)
    print("[DEEPMIND-ONLY] train-easy + train-medium + train-hard", flush=True)
    print("[DEEPMIND-ONLY] linear_1d + linear_2d + polynomial_roots", flush=True)
    print("[DEEPMIND-ONLY] project synthetic generator: DISABLED", flush=True)
    print("[DEEPMIND-ONLY] project augmentation: DISABLED", flush=True)
    return worker


core.prepare_turbo_worker = prepare_turbo_worker_deepmind_only


def cleanup_large_temporaries():
    for p in [
        pathlib.Path("/kaggle/working/mathematics_dataset-v1.0.tar.gz"),
        pathlib.Path("/kaggle/working/mathai_dm_extract"),
        pathlib.Path("/kaggle/working/mathematics_dataset"),
        pathlib.Path("/kaggle/working/Al"),
        CORE_PATH,
    ]:
        try:
            if p.is_dir():
                shutil.rmtree(p, ignore_errors=True)
            elif p.exists():
                p.unlink()
        except Exception as exc:
            print("[CLEANUP]", p, exc, flush=True)


try:
    core.main()
finally:
    cleanup_large_temporaries()
